In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("/content/kick_starter.csv")

In [ ]:
df.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,0.0,1533.95
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,100.0,2421.0,30000.00
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,220.0,45000.00
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,1.0,5000.00
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,1283.0,19500.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 15 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                378661 non-null  int64
 1   name              378657 non-null  object
 2   category          378661 non-null  object
 3   main_category     378661 non-null  object
 4   currency          378661 non-null  object
 5   deadline          378661 non-null  object
 6   goal              378661 non-null  float64
 7   launched          378661 non-null  object
 8   pledged           378661 non-null  float64
 9   state             378661 non-null  object
 10  backers           378661 non-null  int64
 11  country           378661 non-null  object
 12  usd pledged       374864 non-null  float64
 13  usd_pledged_real  378661 non-null  float64
 14  usd_goal_real     378661 non-null  float64
dtypes: float64(5), int64(2), object(8)
memory usage: 43.3+ MB

In [ ]:
print(df[df["name"].isna()])

                ID name        category main_category currency    deadline  \
166851  1848699072  NaN  Narrative Film  Film & Video      USD  2012-02-29
307234   634871725  NaN     Video Games         Games      GBP  2013-01-06
309991   648853978  NaN  Product Design        Design      USD  2016-07-18
338931   796533179  NaN        Painting           Art      USD  2011-12-05

            goal             launched  pledged      state  backers country  \
166851  200000.0  2012-01-01 12:35:31    100.0     failed        1      US
307234    2000.0  2012-12-19 23:57:48    196.0     failed       12      GB
309991    2500.0  2016-06-18 05:01:47      0.0  suspended        0      US
338931   35000.0  2011-11-06 23:55:55    220.0     failed        5      US

        usd pledged  usd_pledged_real  usd_goal_real
166851       100.00            100.00      200000.00
307234       317.73            316.05        3224.97
309991         0.00              0.00        2500.00
338931       220.00            220.00       35000.00

In [ ]:
print(df[df['pledged']!=df["usd_pledged_real"]])

                ID                                               name  \
14      1000057089  Tombstone: Old West tabletop game and miniatur...
21      1000081649                   MikeyJ clothing brand fundraiser
23      1000087442  Mountain brew: A quest for alcohol sustainability
27      1000104688                                Permaculture Skills
28      1000104953  Rebel Army Origins: The Heroic Story Of Major ...
...            ...                                                ...
378636   999877902                      Little Saturday's Debut Album
378642   999929142  ÉPOUVANTAILS : 28mm Figurines de jeux pour KIN...
378645   999941823        The Chronicles of Erinoth - A Graphic Novel
378651   999969812                                       AT THE BEACH
378652   999971898                        Beach Wrestling Documentary

               category main_category currency    deadline     goal  \
14       Tabletop Games         Games      GBP  2017-05-03   5000.0
21        Childrenswear       Fashion      AUD  2017-09-07   2500.0
23               Drinks          Food      NOK  2015-02-25    500.0
27            Webseries  Film & Video      CAD  2014-12-14  17757.0
28               Comics        Comics      GBP  2016-01-28    100.0
...                 ...           ...      ...         ...      ...
378636   Country & Folk         Music      CAD  2014-12-17   5000.0
378642   Tabletop Games         Games      EUR  2017-10-31   1000.0
378645           Comics        Comics      GBP  2013-10-10  16000.0
378651  Classical Music         Music      CAD  2014-03-22   5000.0
378652      Documentary  Film & Video      NOK  2015-04-28  20000.0

                   launched   pledged       state  backers country  \
14      2017-04-05 19:44:18  94175.00  successful      761      GB
21      2017-08-08 01:20:20      1.00      failed        1      AU
23      2015-01-26 19:17:33     48.00      failed        3      NO
27      2014-11-14 18:02:00  48905.00  successful      571      CA
28      2015-12-29 16:59:29    112.38  successful       27      GB
...                     ...       ...         ...      ...     ...
378636  2014-11-17 17:50:12   5435.00  successful       78      CA
378642  2017-10-04 11:26:44   1246.00  successful       35      FR
378645  2013-09-10 22:45:26   2738.00      failed       38      GB
378651  2014-02-20 01:00:16   5501.00  successful       78      CA
378652  2015-03-29 21:30:33  21500.00  successful       36      NO

        usd pledged  usd_pledged_real  usd_goal_real
14         57763.78         121857.33        6469.73
21             0.00              0.81        2026.10
23             6.18              6.29          65.55
27         43203.25          42174.03       15313.04
28           167.70            160.60         142.91
...             ...               ...            ...
378636      4814.88           4686.96        4311.83
378642        66.72           1452.47        1165.70
378645      4281.15           4374.99       25566.05
378651      5019.92           4983.69        4529.81
378652      2698.97           2875.83        2675.19

[69489 rows x 15 columns]

In [ ]:
df.loc[:,['usd_pledged_real','usd pledged']]

        usd_pledged_real  usd pledged
0                    0.0          0.0
1                 2421.0        100.0
2                  220.0        220.0
3                    1.0          1.0
4                 1283.0       1283.0
...                  ...          ...
378656              25.0         25.0
378657             155.0        155.0
378658              20.0         20.0
378659             200.0        200.0
378660             524.0        524.0

[378661 rows x 2 columns]

In [ ]:
print(df[(df['usd pledged'] != df['usd_pledged_real']) & (df['currency'] == 'USD')])

                ID                                               name  \
1       1000003930      Greeting From Earth: ZGAC Arts Capsule For ET
29       100011318                      My Moon - Animated Short Film
31      1000117861                  Ledr workbook: one tough journal!
41      1000153208    Phil Younger - Slow Down (Official Music Video)
43      1000170964  Penny Bingo Playing Card Game fun for the whol...
...            ...                                                ...
378611   999753943                 Parti Bash Mobile App & Technology
378619   999780798                                   Green City Times
378637   999878813                           Ways to Look at the Moon
378649   999963618      Colorado International Activism Film Festival
378654   999975836              Homemade fresh dog food, Cleveland OH

              category main_category currency    deadline     goal  \
1       Narrative Film  Film & Video      USD  2017-11-01  30000.0
29           Animation  Film & Video      USD  2017-05-03  50000.0
31      Product Design        Design      USD  2016-10-08   1000.0
41               Music         Music      USD  2016-12-20   2100.0
43      Tabletop Games         Games      USD  2017-03-27   1500.0
...                ...           ...      ...         ...      ...
378611            Apps    Technology      USD  2017-01-07  25000.0
378619             Web    Journalism      USD  2016-08-28   5000.0
378637          Shorts  Film & Video      USD  2017-10-13  10000.0
378649  Narrative Film  Film & Video      USD  2017-04-09    500.0
378654     Small Batch          Food      USD  2017-04-19   6500.0

                   launched   pledged       state  backers country  \
1       2017-09-02 04:43:57   2421.00      failed       15      US
29      2017-04-03 17:11:33  57577.31  successful      840      US
31      2016-09-07 13:14:26  47266.00  successful      549      US
41      2016-12-09 20:27:02   2100.00  successful       34      US
43      2017-03-02 04:01:43    856.00      failed       25      US
...                     ...       ...         ...      ...     ...
378611  2016-11-08 23:40:40    120.00      failed        2      US
378619  2016-07-29 05:27:43     11.00      failed        3      US
378637  2017-08-29 06:57:28  10245.00  successful      123      US
378649  2017-02-08 02:28:44    135.00      failed        6      US
378654  2017-03-20 22:08:22    154.00      failed        4      US

        usd pledged  usd_pledged_real  usd_goal_real
1             100.0           2421.00        30000.0
29          10120.0          57577.31        50000.0
31          11253.0          47266.00         1000.0
41             83.0           2100.00         2100.0
43            324.0            856.00         1500.0
...             ...               ...            ...
378611         70.0            120.00        25000.0
378619          0.0             11.00         5000.0
378637        145.0          10245.00        10000.0
378649         45.0            135.00          500.0
378654          0.0            154.00         6500.0

[46581 rows x 15 columns]

The column 'usd pledged' has many incorrect values so we decided to drop it completely

In [ ]:
df_clean=df.copy()
df_clean.drop('usd pledged',axis=1,inplace=True)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378661 entries, 0 to 378660
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                378661 non-null  int64
 1   name              378657 non-null  object
 2   category          378661 non-null  object
 3   main_category     378661 non-null  object
 4   currency          378661 non-null  object
 5   deadline          378661 non-null  object
 6   goal              378661 non-null  float64
 7   launched          378661 non-null  object
 8   pledged           378661 non-null  float64
 9   state             378661 non-null  object
 10  backers           378661 non-null  int64
 11  country           378661 non-null  object
 12  usd_pledged_real  378661 non-null  float64
 13  usd_goal_real     378661 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 40.4+ MB

The dataset has only 4 missing values for the column 'name' which is negligible so we decided to drop the rows with those missing values.

In [ ]:
df_clean.dropna(inplace=True)
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 378657 entries, 0 to 378660
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                378657 non-null  int64
 1   name              378657 non-null  object
 2   category          378657 non-null  object
 3   main_category     378657 non-null  object
 4   currency          378657 non-null  object
 5   deadline          378657 non-null  object
 6   goal              378657 non-null  float64
 7   launched          378657 non-null  object
 8   pledged           378657 non-null  float64
 9   state             378657 non-null  object
 10  backers           378657 non-null  int64
 11  country           378657 non-null  object
 12  usd_pledged_real  378657 non-null  float64
 13  usd_goal_real     378657 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 43.3+ MB

In [ ]:
print(df_clean.duplicated().sum())

# No duplicates were found

0

In [ ]:
print(type(df_clean.loc[0,"deadline"]))
print(type(df_clean.loc[0,"launched"]))

<class 'str'>
<class 'str'>

The 'deadline' and 'launched' columns have string data type instead of date, so we changed their types.

In [ ]:
df_clean['deadline']=pd.to_datetime(df_clean['deadline'])
df_clean['launched']=pd.to_datetime(df_clean['launched'])
df_clean.head()
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 378657 entries, 0 to 378660
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                378657 non-null  int64
 1   name              378657 non-null  object
 2   category          378657 non-null  object
 3   main_category     378657 non-null  object
 4   currency          378657 non-null  object
 5   deadline          378657 non-null  datetime64[ns]
 6   goal              378657 non-null  float64
 7   launched          378657 non-null  datetime64[ns]
 8   pledged           378657 non-null  float64
 9   state             378657 non-null  object
 10  backers           378657 non-null  int64
 11  country           378657 non-null  object
 12  usd_pledged_real  378657 non-null  float64
 13  usd_goal_real     378657 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(2), object(6)
memory usage: 51.4+ MB

In [ ]:
df_clean['state'].unique()

array(['failed', 'canceled', 'successful', 'live', 'undefined',
       'suspended'], dtype=object)

In [ ]:
df_clean=df_clean[df_clean['state']!='live']

In [ ]:
df_clean['CampaignDuration']=(df_clean['deadline']-df_clean['launched']).dt.days
df_clean['FundingRatio']=df_clean['usd_pledged_real']/df_clean['usd_goal_real']

def categorize_goal(goal):
    if goal < 10000:
        return "Low"
    elif 10000 <= goal <= 100000:
        return "Medium"
    else:
        return "High"
df_clean["GoalCategory"] = df_clean["usd_goal_real"].apply(categorize_goal)

df_clean['LaunchMonth']=df_clean['launched'].dt.month
df_clean.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio,GoalCategory,LaunchMonth
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0,GB,0.0,1533.95,58,0.000000,Low,8
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15,US,2421.0,30000.00,59,0.080700,Medium,9
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3,US,220.0,45000.00,44,0.004889,Medium,1
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1,US,1.0,5000.00,29,0.000200,Low,3
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14,US,1283.0,19500.00,55,0.065795,Medium,7

In [ ]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 375858 entries, 0 to 378660
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                375858 non-null  int64
 1   name              375858 non-null  object
 2   category          375858 non-null  object
 3   main_category     375858 non-null  object
 4   currency          375858 non-null  object
 5   deadline          375858 non-null  datetime64[ns]
 6   goal              375858 non-null  float64
 7   launched          375858 non-null  datetime64[ns]
 8   pledged           375858 non-null  float64
 9   state             375858 non-null  object
 10  backers           375858 non-null  int64
 11  country           375858 non-null  object
 12  usd_pledged_real  375858 non-null  float64
 13  usd_goal_real     375858 non-null  float64
 14  CampaignDuration  375858 non-null  int64
 15  FundingRatio      375858 non-null  float64
 16  GoalCategory      375858 non-null  object
 17  LaunchMonth       375858 non-null  int32
dtypes: datetime64[ns](2), float64(5), int32(1), int64(3), object(7)
memory usage: 53.1+ MB

In [ ]:
df_clean.to_csv("df_clean.csv")

In [ ]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting dnspython<3.0.0,>=2.6.1 (from pymongo)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 10.7 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 19.1 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.8.0 pymongo-4.16.0

In [ ]:
import pymongo
from pymongo import MongoClient
import urllib.parse
from bson.json_util import dumps

In [ ]:
url = "mongodb+srv://AnthonyShady:tony2005@cluster0.ogh6ppe.mongodb.net/" # replace <<CLUSTERNAME>> with your cluster's name
cluster = MongoClient(url)

In [ ]:
db = cluster["kickstart"]
collection = db["projects"]

In [ ]:
collection.insert_many(df_clean.to_dict(orient='records'))

In [ ]:
  # What is the success rate for each main category?

results = list(collection.aggregate([
  {
    "$group": {
      "_id": "$main_category",
      "total": { "$sum": 1 },
      "success_count": { "$sum": { "$cond": [{ "$eq": ["$state", "successful"] }, 1, 0] } }
    }
  },
  {
    "$project": {
      "_id": 0,
      "category": "$_id",
      "total": 1,
      "success_count": 1,
      "success_rate": { "$multiply": [{ "$divide": ["$success_count", "$total"] }, 100] }
    }
  },
   {"$sort": {"success_rate":-1}}
]))

print(dumps(results, indent=3))

[
   {
      "total": 5775,
      "success_count": 3591,
      "category": "Dance",
      "success_rate": 62.18181818181818
   },
   {
      "total": 16618,
      "success_count": 9964,
      "category": "Theater",
      "success_rate": 59.959080515104105
   },
   {
      "total": 16485,
      "success_count": 8958,
      "category": "Comics",
      "success_rate": 54.340309372156504
   },
   {
      "total": 79030,
      "success_count": 37075,
      "category": "Music",
      "success_rate": 46.9125648487916
   },
   {
      "total": 42794,
      "success_count": 17608,
      "category": "Art",
      "success_rate": 41.14595504042623
   },
   {
      "total": 97066,
      "success_count": 36262,
      "category": "Film & Video",
      "success_rate": 37.35808625059238
   },
   {
      "total": 53613,
      "success_count": 19274,
      "category": "Games",
      "success_rate": 35.95023595023595
   },
   {
      "total": 45638,
      "success_count": 16205,
      "category": "Design",
      "success_rate": 35.50769095928831
   },
   {
      "total": 60693,
      "success_count": 18943,
      "category": "Publishing",
      "success_rate": 31.211177565781885
   },
   {
      "total": 16413,
      "success_count": 5041,
      "category": "Photography",
      "success_rate": 30.713458843599582
   },
   {
      "total": 37450,
      "success_count": 9323,
      "category": "Food",
      "success_rate": 24.89452603471295
   },
   {
      "total": 34451,
      "success_count": 8523,
      "category": "Fashion",
      "success_rate": 24.73948506574555
   },
   {
      "total": 13425,
      "success_count": 3273,
      "category": "Crafts",
      "success_rate": 24.379888268156424
   },
   {
      "total": 7217,
      "success_count": 1554,
      "category": "Journalism",
      "success_rate": 21.532492725509215
   },
   {
      "total": 49190,
      "success_count": 9841,
      "category": "Technology",
      "success_rate": 20.006098800569223
   }
]

In [ ]:
#  Which countries have the highest average pledged amount in USD?

results = list(collection.aggregate([
  {
    "$group": {
      "_id": "$country",
      "avg_pledged": { "$avg": "$usd_pledged_real" }
    }
  },
  {
    "$project": {
      "_id": 0,
      "country": "$_id",
      "avg_pledged": 1
    }
  },
  {
    "$sort": { "avg_pledged": -1 }
  }
 #,{  "$limit": 5} If you want 5 only
]))

print(dumps(results, indent=3))

[
   {
      "avg_pledged": 18847.07056792873,
      "country": "AT"
   },
   {
      "avg_pledged": 17473.67998231653,
      "country": "CH"
   },
   {
      "avg_pledged": 16428.061477777777,
      "country": "HK"
   },
   {
      "avg_pledged": 11921.547387755101,
      "country": "FR"
   },
   {
      "avg_pledged": 10973.4235235732,
      "country": "SG"
   },
   {
      "avg_pledged": 10466.607971349353,
      "country": "NL"
   },
   {
      "avg_pledged": 9809.370347033424,
      "country": "DE"
   },
   {
      "avg_pledged": 9681.278363114667,
      "country": "US"
   },
   {
      "avg_pledged": 7556.514983050848,
      "country": "SE"
   },
   {
      "avg_pledged": 7013.875989621071,
      "country": "GB"
   },
   {
      "avg_pledged": 6721.267832250443,
      "country": "DK"
   },
   {
      "avg_pledged": 6660.014736842106,
      "country": "LU"
   },
   {
      "avg_pledged": 6504.149695652173,
      "country": "BE"
   },
   {
      "avg_pledged": 6034.090456163774,
      "country": "CA"
   },
   {
      "avg_pledged": 5745.125577927548,
      "country": "AU"
   },
   {
      "avg_pledged": 5591.6872872960375,
      "country": "ES"
   },
   {
      "avg_pledged": 5499.160344669118,
      "country": "NZ"
   },
   {
      "avg_pledged": 5298.268870485393,
      "country": "IT"
   },
   {
      "avg_pledged": 5243.985904211395,
      "country": "IE"
   },
   {
      "avg_pledged": 3631.004066543438,
      "country": "NO"
   },
   {
      "avg_pledged": 3172.997801724138,
      "country": "N,0\""
   },
   {
      "avg_pledged": 2727.4925,
      "country": "JP"
   },
   {
      "avg_pledged": 1371.1335490273918,
      "country": "MX"
   }
]

In [ ]:
# Which 5 projects have the highest funding ratio?

results = list(collection.aggregate([
  {
    "$project": {
      "_id": 0,
      "name": 1,
      "main_category": 1,
      "usd_pledged_real": 1,
      "usd_goal_real": 1,
      "FundingRatio": 1
    }
  },
  {
    "$sort": { "FundingRatio": -1 }
  },
  {
    "$limit": 5
  }
]))

print(dumps(results, indent=3))

[
   {
      "name": "VULFPECK /// The Beautiful Game",
      "main_category": "Music",
      "usd_pledged_real": 104277.89,
      "usd_goal_real": 1.0,
      "FundingRatio": 104277.89
   },
   {
      "name": "Re-covering with Friends",
      "main_category": "Music",
      "usd_pledged_real": 68764.1,
      "usd_goal_real": 1.0,
      "FundingRatio": 68764.1
   },
   {
      "name": "Re-covering with Friends",
      "main_category": "Music",
      "usd_pledged_real": 68764.1,
      "usd_goal_real": 1.0,
      "FundingRatio": 68764.1
   },
   {
      "name": "VULFPECK /// Thrill of the Arts",
      "main_category": "Music",
      "usd_pledged_real": 55266.57,
      "usd_goal_real": 1.0,
      "FundingRatio": 55266.57
   },
   {
      "name": "Energy Hook",
      "main_category": "Games",
      "usd_pledged_real": 41535.01,
      "usd_goal_real": 1.0,
      "FundingRatio": 41535.01
   }
]

In [ ]:
# Among failed projects, which category has the highest number of failures?
# This is if main category is intended
results = list(collection.aggregate([
  {
    "$match": { "state": "failed" }
  },
  {
    "$group": {
      "_id": "$main_category",
      "failure_count": { "$sum": 1 }
    }
  },
  {
    "$project": {
      "_id": 0,
      "main_category": "$_id",
      "failure_count": 1
    }
  },
  {
    "$sort": { "failure_count": -1 }
  }
]))

print(dumps(results, indent=3))

[
   {
      "failure_count": 50444,
      "main_category": "Film & Video"
   },
   {
      "failure_count": 35417,
      "main_category": "Publishing"
   },
   {
      "failure_count": 33242,
      "main_category": "Music"
   },
   {
      "failure_count": 31552,
      "main_category": "Technology"
   },
   {
      "failure_count": 24551,
      "main_category": "Games"
   },
   {
      "failure_count": 24525,
      "main_category": "Food"
   },
   {
      "failure_count": 22681,
      "main_category": "Design"
   },
   {
      "failure_count": 21669,
      "main_category": "Fashion"
   },
   {
      "failure_count": 21584,
      "main_category": "Art"
   },
   {
      "failure_count": 9773,
      "main_category": "Photography"
   },
   {
      "failure_count": 8738,
      "main_category": "Crafts"
   },
   {
      "failure_count": 6184,
      "main_category": "Comics"
   },
   {
      "failure_count": 5674,
      "main_category": "Theater"
   },
   {
      "failure_count": 4779,
      "main_category": "Journalism"
   },
   {
      "failure_count": 1908,
      "main_category": "Dance"
   }
]

In [ ]:
# Among failed projects, which category has the highest number of failures?
# This is if sub category is intended
results = list(collection.aggregate([
  {
    "$match": { "state": "failed" }
  },
  {
    "$group": {
      "_id": "$category",
      "failure_count": { "$sum": 1 }
    }
  },
  {
    "$project": {
      "_id": 0,
      "category": "$_id",
      "failure_count": 1
    }
  },
  {
    "$sort": { "failure_count": -1 }
  }
]))

print(dumps(results, indent=3))

[
   {
      "failure_count": 16332,
      "category": "Product Design"
   },
   {
      "failure_count": 13240,
      "category": "Documentary"
   },
   {
      "failure_count": 10921,
      "category": "Food"
   },
   {
      "failure_count": 10651,
      "category": "Video Games"
   },
   {
      "failure_count": 9444,
      "category": "Music"
   },
   {
      "failure_count": 8991,
      "category": "Fiction"
   },
   {
      "failure_count": 8550,
      "category": "Film & Video"
   },
   {
      "failure_count": 8133,
      "category": "Fashion"
   },
   {
      "failure_count": 7988,
      "category": "Nonfiction"
   },
   {
      "failure_count": 7512,
      "category": "Apps"
   },
   {
      "failure_count": 7207,
      "category": "Apparel"
   },
   {
      "failure_count": 7194,
      "category": "Shorts"
   },
   {
      "failure_count": 6755,
      "category": "Technology"
   },
   {
      "failure_count": 6238,
      "category": "Art"
   },
   {
      "failure_count": 5927,
      "category": "Tabletop Games"
   },
   {
      "failure_count": 5887,
      "category": "Children's Books"
   },
   {
      "failure_count": 5866,
      "category": "Web"
   },
   {
      "failure_count": 5285,
      "category": "Webseries"
   },
   {
      "failure_count": 5170,
      "category": "Publishing"
   },
   {
      "failure_count": 5143,
      "category": "Photography"
   },
   {
      "failure_count": 4518,
      "category": "Crafts"
   },
   {
      "failure_count": 4330,
      "category": "Hip-Hop"
   },
   {
      "failure_count": 4222,
      "category": "Rock"
   },
   {
      "failure_count": 4006,
      "category": "Narrative Film"
   },
   {
      "failure_count": 3487,
      "category": "Theater"
   },
   {
      "failure_count": 3354,
      "category": "Software"
   },
   {
      "failure_count": 3294,
      "category": "Design"
   },
   {
      "failure_count": 3178,
      "category": "Comics"
   },
   {
      "failure_count": 3169,
      "category": "Restaurants"
   },
   {
      "failure_count": 2916,
      "category": "Hardware"
   },
   {
      "failure_count": 2908,
      "category": "Painting"
   },
   {
      "failure_count": 2865,
      "category": "Games"
   },
   {
      "failure_count": 2645,
      "category": "Indie Rock"
   },
   {
      "failure_count": 2573,
      "category": "Accessories"
   },
   {
      "failure_count": 2381,
      "category": "Mixed Media"
   },
   {
      "failure_count": 2345,
      "category": "Gadgets"
   },
   {
      "failure_count": 2338,
      "category": "Drinks"
   },
   {
      "failure_count": 2334,
      "category": "Animation"
   },
   {
      "failure_count": 2282,
      "category": "Pop"
   },
   {
      "failure_count": 2127,
      "category": "Country & Folk"
   },
   {
      "failure_count": 2089,
      "category": "Food Trucks"
   },
   {
      "failure_count": 2003,
      "category": "Mobile Games"
   },
   {
      "failure_count": 1985,
      "category": "Public Art"
   },
   {
      "failure_count": 1941,
      "category": "Illustration"
   },
   {
      "failure_count": 1833,
      "category": "Electronic Music"
   },
   {
      "failure_count": 1783,
      "category": "Comedy"
   },
   {
      "failure_count": 1700,
      "category": "Art Books"
   },
   {
      "failure_count": 1682,
      "category": "Drama"
   },
   {
      "failure_count": 1628,
      "category": "Journalism"
   },
   {
      "failure_count": 1613,
      "category": "Graphic Design"
   },
   {
      "failure_count": 1610,
      "category": "Small Batch"
   },
   {
      "failure_count": 1590,
      "category": "Performance Art"
   },
   {
      "failure_count": 1588,
      "category": "Playing Cards"
   },
   {
      "failure_count": 1543,
      "category": "World Music"
   },
   {
      "failure_count": 1460,
      "category": "Sculpture"
   },
   {
      "failure_count": 1356,
      "category": "Comic Books"
   },
   {
      "failure_count": 1317,
      "category": "DIY"
   },
   {
      "failure_count": 1237,
      "category": "Digital Art"
   },
   {
      "failure_count": 1236,
      "category": "Farms"
   },
   {
      "failure_count": 1235,
      "category": "Photobooks"
   },
   {
      "failure_count": 1216,
      "category": "Classical Music"
   },
   {
      "failure_count": 1196,
      "category": "Woodworking"
   },
   {
      "failure_count": 1171,
      "category": "Jewelry"
   },
   {
      "failure_count": 1148,
      "category": "Poetry"
   },
   {
      "failure_count": 1116,
      "category": "People"
   },
   {
      "failure_count": 1082,
      "category": "Television"
   },
   {
      "failure_count": 1074,
      "category": "Horror"
   },
   {
      "failure_count": 1054,
      "category": "Live Games"
   },
   {
      "failure_count": 1036,
      "category": "Dance"
   },
   {
      "failure_count": 1019,
      "category": "Graphic Novels"
   },
   {
      "failure_count": 976,
      "category": "Jazz"
   },
   {
      "failure_count": 961,
      "category": "Periodicals"
   },
   {
      "failure_count": 921,
      "category": "Ready-to-wear"
   },
   {
      "failure_count": 889,
      "category": "Academic"
   },
   {
      "failure_count": 864,
      "category": "Wearables"
   },
   {
      "failure_count": 860,
      "category": "Faith"
   },
   {
      "failure_count": 858,
      "category": "Events"
   },
   {
      "failure_count": 842,
      "category": "Conceptual Art"
   },
   {
      "failure_count": 833,
      "category": "Young Adult"
   },
   {
      "failure_count": 810,
      "category": "Places"
   },
   {
      "failure_count": 772,
      "category": "Action"
   },
   {
      "failure_count": 741,
      "category": "Footwear"
   },
   {
      "failure_count": 741,
      "category": "Plays"
   },
   {
      "failure_count": 719,
      "category": "Architecture"
   },
   {
      "failure_count": 717,
      "category": "Spaces"
   },
   {
      "failure_count": 710,
      "category": "Experimental"
   },
   {
      "failure_count": 708,
      "category": "Radio & Podcasts"
   },
   {
      "failure_count": 704,
      "category": "Print"
   },
   {
      "failure_count": 665,
      "category": "Thrillers"
   },
   {
      "failure_count": 610,
      "category": "Nature"
   },
   {
      "failure_count": 599,
      "category": "Music Videos"
   },
   {
      "failure_count": 594,
      "category": "Fine Art"
   },
   {
      "failure_count": 577,
      "category": "Science Fiction"
   },
   {
      "failure_count": 573,
      "category": "Metal"
   },
   {
      "failure_count": 571,
      "category": "DIY Electronics"
   },
   {
      "failure_count": 563,
      "category": "Musical"
   },
   {
      "failure_count": 523,
      "category": "Vegan"
   },
   {
      "failure_count": 522,
      "category": "Performances"
   },
   {
      "failure_count": 510,
      "category": "3D Printing"
   },
   {
      "failure_count": 507,
      "category": "Childrenswear"
   },
   {
      "failure_count": 507,
      "category": "Video"
   },
   {
      "failure_count": 498,
      "category": "Cookbooks"
   },
   {
      "failure_count": 490,
      "category": "Farmer's Markets"
   },
   {
      "failure_count": 490,
      "category": "Candles"
   },
   {
      "failure_count": 481,
      "category": "Festivals"
   },
   {
      "failure_count": 457,
      "category": "R&B"
   },
   {
      "failure_count": 430,
      "category": "Sound"
   },
   {
      "failure_count": 428,
      "category": "Flight"
   },
   {
      "failure_count": 410,
      "category": "Interactive Design"
   },
   {
      "failure_count": 398,
      "category": "Robots"
   },
   {
      "failure_count": 384,
      "category": "Audio"
   },
   {
      "failure_count": 364,
      "category": "Webcomics"
   },
   {
      "failure_count": 352,
      "category": "Family"
   },
   {
      "failure_count": 339,
      "category": "Anthologies"
   },
   {
      "failure_count": 315,
      "category": "Installations"
   },
   {
      "failure_count": 312,
      "category": "Community Gardens"
   },
   {
      "failure_count": 301,
      "category": "Fantasy"
   },
   {
      "failure_count": 297,
      "category": "Couture"
   },
   {
      "failure_count": 295,
      "category": "Gaming Hardware"
   },
   {
      "failure_count": 270,
      "category": "Textiles"
   },
   {
      "failure_count": 265,
      "category": "Zines"
   },
   {
      "failure_count": 265,
      "category": "Animals"
   },
   {
      "failure_count": 261,
      "category": "Civic Design"
   },
   {
      "failure_count": 254,
      "category": "Space Exploration"
   },
   {
      "failure_count": 247,
      "category": "Camera Equipment"
   },
   {
      "failure_count": 246,
      "category": "Calendars"
   },
   {
      "failure_count": 234,
      "category": "Fabrication Tools"
   },
   {
      "failure_count": 223,
      "category": "Printing"
   },
   {
      "failure_count": 222,
      "category": "Bacon"
   },
   {
      "failure_count": 219,
      "category": "Ceramics"
   },
   {
      "failure_count": 218,
      "category": "Movie Theaters"
   },
   {
      "failure_count": 216,
      "category": "Photo"
   },
   {
      "failure_count": 213,
      "category": "Kids"
   },
   {
      "failure_count": 208,
      "category": "Makerspaces"
   },
   {
      "failure_count": 198,
      "category": "Video Art"
   },
   {
      "failure_count": 194,
      "category": "Immersive"
   },
   {
      "failure_count": 190,
      "category": "Punk"
   },
   {
      "failure_count": 182,
      "category": "Literary Journals"
   },
   {
      "failure_count": 179,
      "category": "Stationery"
   },
   {
      "failure_count": 174,
      "category": "Crochet"
   },
   {
      "failure_count": 174,
      "category": "Blues"
   },
   {
      "failure_count": 168,
      "category": "Puzzles"
   },
   {
      "failure_count": 160,
      "category": "Romance"
   },
   {
      "failure_count": 160,
      "category": "Translations"
   },
   {
      "failure_count": 145,
      "category": "Workshops"
   },
   {
      "failure_count": 132,
      "category": "Latin"
   },
   {
      "failure_count": 131,
      "category": "Glass"
   },
   {
      "failure_count": 120,
      "category": "Knitting"
   },
   {
      "failure_count": 120,
      "category": "Embroidery"
   },
   {
      "failure_count": 119,
      "category": "Pet Fashion"
   },
   {
      "failure_count": 92,
      "category": "Quilts"
   },
   {
      "failure_count": 82,
      "category": "Weaving"
   },
   {
      "failure_count": 69,
      "category": "Pottery"
   },
   {
      "failure_count": 52,
      "category": "Typography"
   },
   {
      "failure_count": 31,
      "category": "Residencies"
   },
   {
      "failure_count": 25,
      "category": "Letterpress"
   },
   {
      "failure_count": 10,
      "category": "Chiptune"
   },
   {
      "failure_count": 9,
      "category": "Literary Spaces"
   },
   {
      "failure_count": 9,
      "category": "Taxidermy"
   }
]

In [ ]:
# What is the average campaign duration for successful vs failed projects?

results = list(collection.aggregate([
  {
    "$match": { "state": { "$in": ["successful", "failed"] } }
  },
  {
    "$group": {
      "_id": "$state",
      "avg_duration": { "$avg": "$CampaignDuration" }
    }
  },
  {
    "$project": {
      "_id": 0,
      "state": "$_id",
      "avg_duration": 1
    }
  }
]))

print(dumps(results, indent=3))

[
   {
      "avg_duration": 31.14834862608611,
      "state": "successful"
   },
   {
      "avg_duration": 34.19432745002825,
      "state": "failed"
   }
]

In [ ]:
# Which month has the highest number of successful projects?

results = list(collection.aggregate([
  {
    "$match": { "state": "successful" }
  },
  {
    "$group": {
      "_id": "$LaunchMonth",
      "success_count": { "$sum": 1 }
    }
  },
  {
    "$project": {
      "_id": 0,
      "month": "$_id",
      "success_count": 1
    }
  },
  {
    "$sort": { "success_count": -1 }
  },
  {
    "$limit": 1
  }
]))

print(dumps(results, indent=3))

[
   {
      "success_count": 19768,
      "month": 3
   }
]

In [ ]:
# What is the average number of backers per main category?

results = list(collection.aggregate([
  {
    "$group": {
      "_id": "$main_category",
      "avg_backers": { "$avg": "$backers" }
    }
  },
  {
    "$project": {
      "_id": 0,
      "main_category": "$_id",
      "avg_backers": 1
    }
  },
  {
    "$sort": { "avg_backers": -1 }
  }
]))

print(dumps(results, indent=3))

[
   {
      "avg_backers": 327.8469774121948,
      "main_category": "Games"
   },
   {
      "avg_backers": 241.02454095271483,
      "main_category": "Design"
   },
   {
      "avg_backers": 163.53529172596055,
      "main_category": "Technology"
   },
   {
      "avg_backers": 135.28983924780104,
      "main_category": "Comics"
   },
   {
      "avg_backers": 66.8482269795809,
      "main_category": "Film & Video"
   },
   {
      "avg_backers": 61.69829613073641,
      "main_category": "Fashion"
   },
   {
      "avg_backers": 55.860000329527296,
      "main_category": "Publishing"
   },
   {
      "avg_backers": 54.386194926568756,
      "main_category": "Food"
   },
   {
      "avg_backers": 51.951233708718206,
      "main_category": "Music"
   },
   {
      "avg_backers": 46.824587796365385,
      "main_category": "Theater"
   },
   {
      "avg_backers": 43.655064935064935,
      "main_category": "Dance"
   },
   {
      "avg_backers": 41.83654250595878,
      "main_category": "Art"
   },
   {
      "avg_backers": 39.87059038566989,
      "main_category": "Photography"
   },
   {
      "avg_backers": 37.78855480116392,
      "main_category": "Journalism"
   },
   {
      "avg_backers": 26.690800744878956,
      "main_category": "Crafts"
   }
]

In [ ]:
# What percentage of projects reached or exceeded their goal?

results = list(collection.aggregate([
  {
    "$group": {
      "_id": None,
      "total_count": { "$sum": 1 },
      "reached_goal_count": { "$sum": { "$cond": [{ "$gte": ["$usd_pledged_real", "$usd_goal_real"] }, 1, 0] } }
    }
  },
  {
    "$project": {
      "_id": 0,
      "total_projects": "$total_count",
      "projects_reached_goal": "$reached_goal_count",
      "percentage": { "$multiply": [{ "$divide": ["$reached_goal_count", "$total_count"] }, 100] }
    }
  }
]))

print(dumps(results, indent=3))

[
   {
      "total_projects": 575858,
      "projects_reached_goal": 209480,
      "percentage": 36.377023502321755
   }
]

In [ ]:
!pip install cassandra-driver

Collecting cassandra-driver
  Downloading cassandra_driver-3.29.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting geomet>=1.1 (from cassandra-driver)
  Downloading geomet-1.1.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from geomet>=1.1->cassandra-driver) (8.3.1)
Downloading cassandra_driver-3.29.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (374 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.4/374.4 kB 16.2 MB/s eta 0:00:00
Downloading geomet-1.1.0-py3-none-any.whl (31 kB)
Installing collected packages: geomet, cassandra-driver
Successfully installed cassandra-driver-3.29.3 geomet-1.1.0

In [ ]:
!python -c "import cassandra; print(cassandra.__version__)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cassandra'

In [ ]:
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

cloud_config= {
        'secure_connect_bundle':'/content/secure-connect-kickstart.zip' # replace <</PATH/TO/>> with the path where your downloaded bundle was uploaded here
        }
auth_provider = PlainTextAuthProvider('YMEqmWtdpjOKBccrHQwTJEHc', 'binNsG,s8uEZvLIkv6_qaQsI5dqoiFsDjSeiER2toXDPC5mKsgatJOB1,oWrrMFi5H9OnbhktDyS3fUo2s72zNGFdZJmr1fn18faIhOjdw9YZN.wUMZ+,.ayz5oCLpUT')
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect()

WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 319146c2-4eb0-4188-b2e5-4eb830842d93-us-east1.db.astra.datastax.com:29042:98a2cd7e-fa1b-3950-942e-42af495c4248. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. https://docs.datastax.com/en/developer/python-driver/latest/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 319146c2-4eb0-4188-b2e5-4eb830842d93-us-east1.db.astra.datastax.com:29042:98a2cd7e-fa1b-3950-942e-42af495c4248. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. https://docs.datastax.com/en/developer/python-driver/latest/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
WARNING:cassandra.cluster:Downgrading core protocol version from 5 to 4 for 319146c2-4eb0-4188-b2e5-4eb830842d93-us-east1.db.astra.datastax.com:29042:98a2cd7e-fa1b-3950-942e-42af495c4248. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. https://docs.datastax.com/en/developer/python-driver/latest/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version

In [ ]:
session.set_keyspace('project') # replace <<KEYSPACENAME>> with the name of the keyspace you created in DataStax
row = cluster.metadata.keyspaces['project'] # replace <<KEYSPACENAME>> with the name of the keyspace you created in DataStax

from pprint import pprint
pprint(vars(row))

{'aggregates': {},
 'durable_writes': True,
 'functions': {},
 'graph_engine': None,
 'indexes': {},
 'name': 'project',
 'replication_strategy': <cassandra.metadata.NetworkTopologyStrategy object at 0x79f47d32d310>,
 'tables': {'kickstarter_projects': <cassandra.metadata.TableMetadataV3 object at 0x79f47d32d7c0>},
 'user_types': {},
 'views': {}}

In [ ]:
df_clean

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio,GoalCategory,LaunchMonth
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0.0,GB,0.00,1533.95,58,0.000000,Low,8
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15.0,US,2421.00,30000.00,59,0.080700,Medium,9
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3.0,US,220.00,45000.00,44,0.004889,Medium,1
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1.0,US,1.00,5000.00,29,0.000200,Low,3
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14.0,US,1283.00,19500.00,55,0.065795,Medium,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20454,1103949925,Seeking Ezra Clothing Launch,Apparel,Fashion,USD,2015-03-31,2000.0,2015-02-22 22:31:23,0.0,failed,0.0,US,0.00,2000.00,36,0.000000,Low,2
20455,1103953511,Many Mansions (Canceled),Drama,Film & Video,USD,2014-07-14,13000.0,2014-07-03 20:38:51,20.0,canceled,1.0,US,20.00,13000.00,10,0.001538,Medium,7
20456,1103972927,Andretti Dante's Insomniac Theatre,Film & Video,Film & Video,USD,2012-06-01,20000.0,2012-05-07 08:31:37,680.0,failed,12.0,US,680.00,20000.00,24,0.034000,Medium,5
20457,1103975038,Location Alarm Phone App (Canceled),Apps,Technology,CAD,2016-01-14,15000.0,2015-12-15 21:21:52,0.0,canceled,0.0,CA,0.00,10329.16,29,0.000000,Medium,12
20458,1103977116,Shakespeare Link goes to Latvia,Performance Art,Art,GBP,2015-07-02,1600.0,2015-06-02 21:56:02,225.0,failed,9.0,GB,351.54,2499.80,29,0.140627,Low,6

In [ ]:
df_clean.info()

In [ ]:
session.execute("""CREATE TABLE kickstarter_projects (
    id bigint PRIMARY KEY,
    name text,
    category text,
    main_category text,
    currency text,
    deadline timestamp,
    goal double,
    launched timestamp,
    pledged double,
    state text,
    backers int,
    country text,
    usd_pledged_real double,
    usd_goal_real double,
    campaign_duration int,
    funding_ratio double,
    goal_category text,
    launch_month int
);""")

In [ ]:
insert_query = session.prepare("""
INSERT INTO kickstarter_projects (
id, name, category, main_category, currency,
deadline, goal, launched, pledged, state,
backers, country, usd_pledged_real, usd_goal_real,
campaign_duration, funding_ratio, goal_category, launch_month
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""")

In [ ]:
from cassandra.query import BatchStatement

batch_size = 300

for start in range(0, len(df_clean), batch_size):

    batch = BatchStatement()
    chunk = df_clean.iloc[start:start+batch_size]

    for _, row in chunk.iterrows():

        batch.add(insert_query, (
            int(row.ID),
            str(row.name),
            str(row.category),
            str(row.main_category),
            str(row.currency),
            row.deadline,
            float(row.goal),
            row.launched,
            float(row.pledged),
            str(row.state),
            int(row.backers),
            str(row.country),
            float(row.usd_pledged_real),
            float(row.usd_goal_real),
            int(row.CampaignDuration),
            float(row.FundingRatio),
            str(row.GoalCategory),
            int(row.LaunchMonth)
        ))

    session.execute(batch)

    print("Inserted rows:", start + len(chunk))

In [ ]:
import pandas as pd

In [ ]:
# What is the success rate for each main category?

rows = session.execute("""
SELECT main_category, state
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

success_rate = (
    df_cassandra.groupby("main_category")["state"]
    .apply(lambda x: (x == "successful").mean())
    .reset_index(name="success_rate")
)

print(success_rate)

   main_category  success_rate
0            Art      0.411689
1         Comics      0.543796
2         Crafts      0.242185
3          Dance      0.623467
4         Design      0.354455
5        Fashion      0.247851
6   Film & Video      0.373474
7           Food      0.249201
8          Games      0.358241
9     Journalism      0.214225
10         Music      0.468598
11   Photography      0.307986
12    Publishing      0.310802
13    Technology      0.199863
14       Theater      0.600993

In [ ]:
#  Which countries have the highest average pledged amount in USD?

rows = session.execute("""
SELECT country, usd_pledged_real
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

avg_pledged = (
    df_cassandra.groupby("country")["usd_pledged_real"]
    .mean()
    .sort_values(ascending=False)
)

print(avg_pledged)

country
CH      17166.342918
HK      16571.635695
AT      16356.804021
FR      11755.749013
SG      10459.981252
NL      10271.864811
US       9690.136026
DE       9654.600488
LU       7671.269508
SE       7599.589413
GB       7049.369687
BE       6897.666793
DK       6892.961349
CA       6205.417259
AU       5982.114455
IT       5773.734615
ES       5711.843750
NZ       5424.757173
IE       5197.639638
NO       3599.009643
N,0"     2950.627692
JP       2918.005806
MX       1439.594298
Name: usd_pledged_real, dtype: float64

In [ ]:
# Among failed projects, which category has the highest number of failures?

rows = session.execute("""
SELECT id, name, funding_ratio
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

top_projects = (
    df_cassandra.sort_values("funding_ratio", ascending=False)
    [["id", "name", "funding_ratio"]]
    .head(5)
)

print(top_projects)

                id    name  funding_ratio
323726     9509582  369176      104277.89
41551   1947298033  186096       68764.10
309933   907870443  360721       55266.57
111119  1388400809   76290       41535.01
313327  1413857335   81368       32843.00

In [ ]:
# Among failed projects, which category has the highest number of failures?

rows = session.execute("""
SELECT category, state
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

failed_categories = (
    df_cassandra[df_cassandra["state"] == "failed"]
    .groupby("category")
    .size()
    .sort_values(ascending=False)
)

print(failed_categories.head(10))

category
Product Design    10718
Documentary        8599
Food               7119
Video Games        6941
Music              6201
Fiction            5875
Film & Video       5554
Fashion            5341
Nonfiction         5184
Apps               4909
dtype: int64

In [ ]:
# What is the average campaign duration for successful vs failed projects?

rows = session.execute("""
SELECT state, campaign_duration
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

avg_duration = (
    df_cassandra.groupby("state")["campaign_duration"]
    .mean()
)

print(avg_duration)

state
canceled      37.269115
failed        34.173350
successful    31.156469
suspended     43.484011
undefined     31.877035
Name: campaign_duration, dtype: float64

In [ ]:
# Which month has the highest number of successful projects?

rows = session.execute("""
SELECT launch_month, state
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

successful_month = (
    df_cassandra[df_cassandra["state"] == "successful"]
    .groupby("launch_month")
    .size()
    .sort_values(ascending=False)
)

print(successful_month)

launch_month
3     12851
10    12350
4     12093
5     12062
6     11773
11    11770
7     11681
9     11231
2     11003
8     10820
1      9480
12     6842
dtype: int64

In [ ]:
# What is the average number of backers per main category?

rows = session.execute("""
SELECT main_category, backers
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

avg_backers = (
    df_cassandra.groupby("main_category")["backers"]
    .mean()
    .sort_values(ascending=False)
)

print(avg_backers)

main_category
Games           323.721718
Design          241.503427
Technology      164.979187
Comics          135.348227
Film & Video     66.273983
Fashion          61.843836
Publishing       56.060240
Food             54.360226
Music            52.312567
Theater          47.132082
Dance            42.952000
Art              42.274984
Photography      39.741497
Journalism       38.361135
Crafts           27.456086
Name: backers, dtype: float64

In [ ]:
# What percentage of projects reached or exceeded their goal?

rows = session.execute("""
SELECT funding_ratio
FROM kickstarter_projects
""")

df_cassandra = pd.DataFrame(list(rows))

goal_percentage = (df_cassandra["funding_ratio"] >= 1).mean() * 100

print("Percentage reaching goal:", goal_percentage)

Percentage reaching goal: 36.343778767513264